### PR TITLE
Prevent needless getDiagnostic calls

### PR DESCRIPTION
**Pull request by BladeMF**
Minor performance improvements in obvious places, e.g. calling `$this->getDiagnostics` in a loop.

### CODE REVIEW

**Comment by BladeMF** [comment]
The tests fail at my end too. I cannot explain why the master branch fails `composer integrate`. I'd welcome help.

**Review by dantleech — APPROVED** [review]

**Comment by dantleech** [comment]
Nice work, looks like multiple dependency issues. Will need to investigate

**Comment by dantleech** [comment]
`mater` should be green now if you can rebase

**Comment by BladeMF** [comment]
Thank you so much, I'll rebase the first chance I get.

**Comment by BladeMF** [comment]
Rebased, it now merges.

**Comment by BladeMF** [comment]
Thanks for the help!

**Comment by dantleech** [comment]
:bow:

**Pull request merged**
